apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-config
  namespace: superset
data:
  superset_config.py: |
    import os
    SECRET_KEY = os.environ.get('SUPERSET_SECRET_KEY')
    SQLALCHEMY_DATABASE_URI = os.environ.get('SUPERSET_DB')
    # Отключаем проверку WTF CSRF для простоты API (рекомендуется включить в проде)
    WTF_CSRF_ENABLED = False
    # Настройки для стабильной работы
    TALISMAN_ENABLED = False
    FEATURE_FLAGS = {}
